services:
  - type: web
    name: smartcars-elite
    env: node
    plan: starter
    buildCommand: curl -fsSL https://bun.sh/install | bash && source ~/.bashrc && bun install && bun run build && bun x drizzle-kit push --force
    startCommand: node dist-server/server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: smartcars-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://smartcars-elite.onrender.com
    autoDeploy: true

databases:
  - name: smartcars-db
    plan: starter
    region: oregon