services:
  - type: web
    name: smartcars-elite
    env: node
    plan: starter
    buildCommand: bun install && bun run build
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: smartcars-db
          property: connectionString
    autoDeploy: false

databases:
  - name: smartcars-db
    plan: starter
    region: oregon